import { Archetype, Attribute, Skill, Upgrade, DefectInsight } from './types';

export const SKILLS_LIST: { name: Skill; attribute: Attribute }[] = [
  { name: Skill.Agility, attribute: Attribute.Physique },
  { name: Skill.CloseCombat, attribute: Attribute.Physique },
  { name: Skill.Force, attribute: Attribute.Physique },
  { name: Skill.Medicine, attribute: Attribute.Precision },
  { name: Skill.RangedCombat, attribute: Attribute.Precision },
  { name: Skill.Stealth, attribute: Attribute.Precision },
  { name: Skill.Investigation, attribute: Attribute.Logic },
  { name: Skill.Learning, attribute: Attribute.Logic },
  { name: Skill.Vigilance, attribute: Attribute.Logic },
  { name: Skill.Inspiration, attribute: Attribute.Empathy },
  { name: Skill.Manipulation, attribute: Attribute.Empathy },
  { name: Skill.Observation, attribute: Attribute.Empathy },
];

export const MEMENTOS: string[] = [
  "Dried red rose", "Photo of someone close to you", "Seal ring with a secret chamber",
  "Your father’s cane", "Hat with a secret compartment", "Book in a foreign language",
  "Hip flask with inscription", "Old love letter", "A scruffy cat", "A monkey’s skull",
  "Bloodstained promissory note", "Gold jewelry worn by your mother", "Silver cross on a chain",
  "Beautiful fiddle passed down in the family", "Journal (yours or someone else’s)",
  "Newspaper from a date that means something to you", "Ragged doll", "Tame pigeon",
  "Well-thumbed novel with dedication", "Plans for a family tomb", "Map with notes in the margin",
  "Strange animal preserved in a glass jar", "Music box from your childhood", "Sunstone (cut mineral)",
  "Small bottle of perfume that reminds you of someone", "Hymnbook passed down in the family",
  "Pocket watch with a photo inside", "An unsigned will", "Golden box from a foreign land",
  "Sheet music from a forgotten master", "Powder compact with sleeping pills", "Beautifully ornamented pipe",
  "Rabbit’s foot or some other lucky charm", "Syringe with needle in a box", "Worn dice made of bone",
  "A manuscript passed down in the family",
];


export const ARCHETYPES: Record<string, Archetype> = {
  Academic: {
    name: 'Academic',
    description: 'A scholar obsessed with uncovering the truth, no matter the cost.',
    mainAttribute: Attribute.Logic,
    mainSkill: Skill.Learning,
    talents: ['Bookworm', 'Erudite', 'Knowledge is Reassuring'],
    equipment: ['Book collection or map book', 'writing utensils', 'liquor or slide rule'],
    resources: [4, 6],
    motivations: ['Charting the unknown', 'Proving my critics wrong', 'Becoming famous'],
    traumas: ['Vaettir turned you into a rat', 'Aged by the magic of a mermaid', 'Watched your partner being torn apart by a giant'],
    darkSecrets: ['Addicted to drugs', 'Stole or falsified documents to get research results', 'Hunted by a vaesen'],
    relationships: ['A tool for my purposes', 'I cannot stay calm in your presence', 'A good friend'],
  },
  Doctor: {
    name: 'Doctor',
    description: 'A medical professional who walks the line between science and the supernatural.',
    mainAttribute: Attribute.Logic,
    mainSkill: Skill.Medicine,
    talents: ['Army Medic', 'Chief Physician', 'Emergency Medicine'],
    equipment: ["Doctor's bag with medical equipment", 'liquor or fine wine', 'weak horse or strong poison'],
    resources: [4, 6],
    motivations: ['Exploring and describing the world', 'Aiding the weak and afflicted', 'Strengthening the Society and becoming its leader'],
    traumas: ['A corpse came back to life during an autopsy', "Operated on a person with donkey's ears and hooves", 'Saw your destiny in the eyes of a dying mermaid'],
    darkSecrets: ['Has two separate personalities', 'Involved in illicit affairs', 'Unnatural lust'],
    relationships: ['I trust you with my secrets', 'You annoy me', 'I dream of you at night'],
  },
  Hunter: {
    name: 'Hunter',
    description: 'At home in the wilds, tracking both mundane beasts and supernatural horrors.',
    mainAttribute: Attribute.Precision,
    mainSkill: Skill.RangedCombat,
    talents: ['Bloodhound', 'Herbalist', 'Marksman'],
    equipment: ['Rifle', 'hunting knife or hunting dog', 'hunting trap or hunting equipment'],
    resources: [2, 4],
    motivations: ['The thing that attacked my family must be destroyed', 'Live in tune with nature', 'Wants to bag some fantastic game'],
    traumas: ['Attacked by the branches of an ash tree wife', "Broke your leg in the forest, but was guided home by a will o' the wisp", 'Captured at dawn by a mountain troll and was stuck in its petrified arms'],
    darkSecrets: ['I sold my soul', 'I cannot control my fits of rage', 'Has children with a vaesen'],
    relationships: ['I am attracted to you', 'I hate bullies like you', "You're a townie weakling"],
  },
  Occultist: {
    name: 'Occultist',
    description: 'A seeker of forbidden knowledge, wielding powers that brush against madness.',
    mainAttribute: Attribute.Precision,
    mainSkill: Skill.Stealth,
    talents: ['Magic tricks', 'Medium', 'Striking Fear'],
    equipment: ["Crystal ball, powdered stag's horn", 'tinder box, dagger or cooking pot'],
    resources: [1, 4],
    motivations: ['Learning about vaesen', 'Understanding myself', 'Power'],
    traumas: ['Was hit by corrosive venom while trying to steal a lindworm egg', 'The family farm is being run by a grumpy house nisse', 'Was attacked by a night raven who infected you with a febrile disease'],
    darkSecrets: ['Guilty of a heinous crime', 'My powers control me', 'Changeling'],
    relationships: ['You are hiding something from the rest of us', 'You bring me peace.', 'You will save us all one day'],
  },
  Officer: {
        name: 'Officer',
        description: 'A disciplined leader, accustomed to command and the rigors of battle.',
        mainAttribute: Attribute.Precision,
        mainSkill: Skill.RangedCombat,
        talents: ['Battle-hardened', 'Gentleman', 'Tactician'],
        equipment: ['Rifle or pistol', 'compass or bayonet', 'map book or saber'],
        resources: [3, 7],
        motivations: ['Make my father proud', 'My friends need me', 'Seek out danger and death'],
        traumas: ['Almost drowned when your ship was dragged down by a sea monster', 'Lost all your men to an angry giant', 'Saw dead warriors rise again on the battlefield'],
        darkSecrets: ['Deserter', 'Cannot cope with filth and disorder', 'Killed a defenseless enemy'],
        relationships: ['Protects you at any cost', 'My leader', 'Distrusts you'],
    },
  Priest: {
    name: 'Priest',
    description: 'A person of faith whose beliefs are tested by the horrors they witness.',
    mainAttribute: Attribute.Empathy,
    mainSkill: Skill.Observation,
    talents: ['Absolution', 'Blessing', 'Confessor'],
    equipment: ['Musical instrument or fine wines', 'writing utensils', 'holy water or old bible'],
    resources: [4, 6],
    motivations: ['Performing a sacred mission', 'Cleansing my tarnished soul', "Understanding God's creation"],
    traumas: ['Hurt someone after being enthralled by a witch', 'Watched a church grim tear apart some thieves', 'Served the church to avoid being twisted'],
    darkSecrets: ['The Devil speaks to me', 'I have stolen my identity', 'Ensnared by a vaesen'],
    relationships: ['I am better than you', 'Secretly in love with you', 'My disciple'],
  },
  PrivateDetective: {
        name: 'Private Detective',
        description: 'A sharp mind who solves mysteries the authorities cannot, or will not, touch.',
        mainAttribute: Attribute.Logic,
        mainSkill: Skill.Investigation,
        talents: ['Eagle Eye', 'Elementary', 'Focused'],
        equipment: ['Magnifying glass or lockpicks', 'revolver', 'knuckle duster or binoculars'],
        resources: [2, 5],
        motivations: ['Getting away from my family', 'Uncovering the truth', 'Thrill-seeking'],
        traumas: ['Heard the cry of a myling during your search for a missing child', 'Had nightmares and woke up breathless and mare-ridden', 'Came face-to-face with a werewolf'],
        darkSecrets: ['There is a price on my head', 'Constant adulterer', 'Drug addict'],
        relationships: ['You think you can trust me', 'A good person', 'Tries to understand you'],
    },
    Servant: {
        name: 'Servant',
        description: 'A loyal and robust individual, often underestimated but privy to many secrets.',
        mainAttribute: Attribute.Physique,
        mainSkill: Skill.Force,
        talents: ['Loyal', 'Robust', 'Tough as Nails'],
        equipment: ['Revolver', 'hurricane lamp or make-up', 'field kitchen or simple bandages'],
        resources: [2, 4],
        motivations: ['Protecting my master', 'Curiosity', 'An urge to help humans and vaesen alike'],
        traumas: ['Bitten by a brook horse', 'Lost a master to the alluring song of the Neck', 'Served a household plagued by a changeling'],
        darkSecrets: ['I murdered someone', 'Persecuted for my religion', 'Spying for a foreign power'],
        relationships: ['At your service', "I don't take orders from you", 'Mutual respect'],
    },
    Vagabond: {
        name: 'Vagabond',
        description: 'A wanderer of the roads, possessing strange tricks and a unique perspective on the world.',
        mainAttribute: Attribute.Physique,
        mainSkill: Skill.Manipulation,
        talents: ['Hobo Tricks', 'Suspicious', 'Well-traveled'],
        equipment: ['Walking stick, knife or crowbar', 'liquor or pet dog'],
        resources: [1, 3],
        motivations: ['Avenging my family', 'Exposing supernatural secrets', 'Being liked'],
        traumas: ['Saw a revenant rise from its grave', 'Forever in love with a wood wife', 'Survived a week inside a troll bag'],
        darkSecrets: ['Stolen identity', 'Terminal illness', 'A vaesen kills anyone I love'],
        relationships: ['You scratch my back, and I’ll scratch yours', 'Feigned gratitude', 'You are my friend'],
    },
  Writer: {
    name: 'Writer',
    description: 'A chronicler of the strange and macabre, driven to capture the truth on paper.',
    mainAttribute: Attribute.Empathy,
    mainSkill: Skill.Inspiration,
    talents: ['Automatic Writing', 'Journalist', 'Wordsmith'],
    equipment: ['Writing utensils and paper', 'camera or opera glasses', 'pet dog or book collection'],
    resources: [2, 5],
    motivations: ['Finding a certain vaesen', 'Researching a book', 'Revenge'],
    traumas: ['Angered fairies who put you to sleep and sucked your blood', 'Cursed by a homeless vaettir to write a book in your own blood', 'Heard the song of the Neck, but failed to write down the lyrics'],
    darkSecrets: ['I record and use the secrets and weaknesses of my friends', 'Wanted for revolutionary ideas', "My life's work is a lie"],
    relationships: ['You inspire me', 'Tries to win your appreciation', 'You frighten me'],
  },
};

export const UPGRADES: Upgrade[] = [
    // Default available
    {id: 'butler', name: 'Butler Algot Frisk', type: 'Personnel', prerequisite: 'Available from start', cost: 0, description: 'Manages the headquarters.', purchased: true},
    {id: 'library', name: 'Library', type: 'Facility', prerequisite: 'Available from start', cost: 0, description: 'Clues can be found here.', purchased: true},
    // Facilities
    {id: 'armory', name: 'Armory', type: 'Facility', prerequisite: 'Resources 5 & Weapons Corridor', cost: 5, description: 'During prep, bring a melee weapon or armor (availability 2) for free.', purchased: false},
    {id: 'butterfly_house', name: 'Butterfly House', type: 'Facility', prerequisite: 'Botanical Garden', cost: 2, description: 'Spend a scene here to heal two mental Conditions.', purchased: false},
    {id: 'carp_pond', name: 'Carp Pond', type: 'Facility', prerequisite: 'Botanical Garden', cost: 2, description: 'Gain an extra Advantage before a mystery: Unwavering Calm.', purchased: false},
    {id: 'infirmary', name: 'Infirmary', type: 'Facility', prerequisite: 'Resources 5 or Doctor', cost: 6, description: 'Makes it possible to push all physical recovery rolls.', purchased: false},
    {id: 'kennel', name: 'Kennel', type: 'Facility', prerequisite: 'Gamekeeper or Hunter', cost: 4, description: 'Bring a guard or hunting dog without using Resources.', purchased: false},
    {id: 'local_tavern', name: 'Local Tavern', type: 'Facility', prerequisite: 'None', cost: 4, description: 'One player character per level can gain +2 to their physical recovery roll.', purchased: false},
    {id: 'map_room', name: 'Map Room', type: 'Facility', prerequisite: 'Library or Professor', cost: 4, description: 'Gain an extra Advantage before a mystery: Old Map.', purchased: false},
    {id: 'observatory', name: 'Observatory', type: 'Facility', prerequisite: 'Patron or Inventor', cost: 5, description: 'Gain an Advantage: Divination or Weather Prophet. Asset: Bring Binoculars for free.', purchased: false},
    {id: 'pigeon_loft', name: 'Pigeon Loft', type: 'Facility', prerequisite: 'Caretaker', cost: 4, description: 'Bring a homing pigeon on a mystery to send for help.', purchased: false},
    {id: 'seance_parlor', name: 'Seance Parlor', type: 'Facility', prerequisite: 'Resources 4 or Occultist', cost: 5, description: 'Hold a séance before a mystery to gain additional clues.', purchased: false},
    {id: 'shooting_range', name: 'Shooting Range', type: 'Facility', prerequisite: 'Weapons Corridor', cost: 5, description: 'Bring a ranged weapon (availability 1-3) for free.', purchased: false},
    {id: 'stable', name: 'Stable', type: 'Facility', prerequisite: 'Resources 5 or Vagabond', cost: 4, description: 'Bring a scrawny horse without using Resources.', purchased: false},
    {id: 'annals_of_society', name: 'The Annals of the Society', type: 'Facility', prerequisite: 'None', cost: 4, description: 'At the end of a session, record experiences to grant each PC one additional XP.', purchased: false},
    {id: 'weapons_corridor', name: 'Weapons Corridor', type: 'Facility', prerequisite: 'Resources 4', cost: 4, description: 'Bring a melee weapon (availability 1) for free.', purchased: false},
    {id: 'workshop', name: 'Workshop', type: 'Facility', prerequisite: 'Resources 4', cost: 4, description: 'Gain an Advantage: Well-Maintained Weapons or Tools.', purchased: false},
    // Discovered Facilities
    {id: 'botanical_garden', name: 'Botanical Garden (Discovered)', type: 'Facility', prerequisite: 'Gardener', cost: 4, description: 'Spend a scene in the garden to heal two mental Conditions.', purchased: false},
    {id: 'cellar_vault', name: 'Cellar Vault (Discovered)', type: 'Facility', prerequisite: 'None', cost: 4, description: 'Store up to 3 common items or weapons from previous mysteries.', purchased: false},
    {id: 'chapel', name: 'Chapel (Discovered)', type: 'Facility', prerequisite: 'Resources 5 or Priest', cost: 6, description: 'Can push all mental recovery rolls. Asset: Bring holy water.', purchased: false},
    {id: 'difference_engine', name: 'Difference Engine (Discovered)', type: 'Facility', prerequisite: 'Inventor', cost: 6, description: 'Facilities cost one less Development point to construct.', purchased: false},
    {id: 'dungeon', name: 'Dungeon (Discovered)', type: 'Facility', prerequisite: 'Cellar Vault', cost: 3, description: 'NPCs imprisoned here cannot escape without help.', purchased: false},
    // Contacts
    {id: 'banker', name: 'Banker', type: 'Contact', prerequisite: 'Resources 5', cost: 5, description: 'Once per mystery, raise Resources by 2 for one scene.', purchased: false},
    {id: 'fixer', name: 'Fixer', type: 'Contact', prerequisite: 'Six or more Facilities', cost: 4, description: 'Restore or retrieve a lost memento without spending XP.', purchased: false},
    {id: 'journalist', name: 'Journalist', type: 'Contact', prerequisite: 'Resources 4 or Writer', cost: 4, description: 'Provides additional clues and can help on mysteries.', purchased: false},
    {id: 'patron', name: 'Patron', type: 'Contact', prerequisite: 'Inspiration 5 or Officer', cost: 4, description: 'Grants a free success on a Manipulation test when bartering.', purchased: false},
    {id: 'police_constable', name: 'Police Constable', type: 'Contact', prerequisite: 'Resources 5 or Private Investigator', cost: 4, description: 'Can provide clues, fabricate evidence, protect against criminals.', purchased: false},
    {id: 'professor', name: 'Professor', type: 'Contact', prerequisite: 'Resources 5 or Academic', cost: 4, description: 'Grants a free success on a roll for finding or understanding information in Upsala.', purchased: false},
    {id: 'psychiatrist', name: 'Psychiatrist', type: 'Contact', prerequisite: 'A PC must have become mentally Broken', cost: 4, description: 'Gives a player character +2 on her mental recovery roll.', purchased: false},
    // Personnel
    {id: 'caretaker', name: 'Caretaker', type: 'Personnel', prerequisite: 'Workshop', cost: 3, description: 'Repairs facilities in the castle if something is broken.', purchased: false},
    {id: 'chef', name: 'Chef', type: 'Personnel', prerequisite: 'None', cost: 4, description: 'Provides each PC with simple provisions during prep for free.', purchased: false},
    {id: 'coachman', name: 'Coachman', type: 'Personnel', prerequisite: 'Stable', cost: 4, description: 'Provides a carriage with two strong horses to travel and heal a Condition.', purchased: false},
    {id: 'gamekeeper', name: 'Gamekeeper', type: 'Personnel', prerequisite: 'Shooting Range', cost: 5, description: 'Upgrades shooting range weapons to availability level 4.', purchased: false},
    {id: 'gardener', name: 'Gardener', type: 'Personnel', prerequisite: 'Resources 5', cost: 4, description: 'All food from the HQ is nutritious. Asset: Provides weak or strong poison.', purchased: false},
    {id: 'guard', name: 'Guard', type: 'Personnel', prerequisite: 'None', cost: 5, description: 'Protects the castle from burglars and enemies.', purchased: false},
    {id: 'house_physician', name: 'House Physician', type: 'Personnel', prerequisite: 'Infirmary', cost: 6, description: 'Automatically treats Broken and two Conditions for all PCs once per mystery.', purchased: false},
    {id: 'inventor', name: 'Inventor', type: 'Personnel', prerequisite: 'Professor', cost: 5, description: 'Build one mechanical item of choice before a mystery. Asset: Provides free chemical equipment.', purchased: false},
    {id: 'mystic', name: 'Mystic', type: 'Personnel', prerequisite: 'Occult Library', cost: 5, description: 'Can gain a clue about a power item or magic item related to the mystery.', purchased: false},
    {id: 'quartermaster', name: 'Quartermaster', type: 'Personnel', prerequisite: 'Banker or Patron', cost: 6, description: 'All player characters gain +2 Capital.', purchased: false},
    {id: 'recruit', name: 'Recruit', type: 'Personnel', prerequisite: 'Inspiration 4', cost: 5, description: 'A new member with the Sight who can come along on mysteries.', purchased: false},
    {id: 'stable_boy', name: 'Stable Boy', type: 'Personnel', prerequisite: 'Stable', cost: 3, description: 'All horses from the headquarters count as strong.', purchased: false},
];

export const TALENT_DESCRIPTIONS: Record<string, string> = {
    // Academic
    'Bookworm': 'Gain +2 to LEARNING when looking for clues in books or libraries.',
    'Erudite': 'You can pass a LEARNING test to establish truths about places and phenomena in the game.',
    'Knowledge is Reassuring': 'Ignore Conditions when making LEARNING tests.',
    // Doctor
    'Army Medic': 'Gain +2 to Fear tests when frightened by dead or damaged human bodies.',
    'Chief Physician': 'When you use MEDICINE to treat other player characters, they can heal a total of four Conditions instead of three.',
    'Emergency Medicine': 'Ignore mental Conditions when using MEDICINE.',
    // Hunter
    'Bloodhound': 'Gain +2 to VIGILANCE when tracking your prey.',
    'Herbalist': 'By utilizing wild herbs, you can use MEDICINE without having access to medical supplies.',
    'Marksman': 'Gain +2 to RANGED COMBAT on your first turn when successfully ambushing or attacking your enemy.',
    // Occultist
    'Magic tricks': 'You can use STEALTH instead of MANIPULATION when performing conjuring tricks to influence people.',
    'Medium': 'You can use OBSERVATION to perform seances where you predict people’s futures and contact the dead.',
    'Striking Fear': 'You can strike fear with Fear 1. It counts as a slow action and does not work against vaesen.',
    // Officer
    'Battle-hardened': 'When drawing for initiative, draw two cards and pick one of them.',
    'Gentleman': 'Ignore penalties from mental Conditions when making MANIPULATION tests.',
    'Tactician': 'When you pass a RANGED COMBAT test with extra successes, you may issue an order to a friend, giving them +2 on their next test.',
    // Priest
    'Absolution': 'A player character who confesses to you heals three Conditions instead of two.',
    'Blessing': 'Once per session you can bless an object or another player character, granting them the Blessed Advantage (+2 to a test).',
    'Confessor': 'You may use OBSERVATION instead of MANIPULATION when having a confidential conversation.',
    // Private Detective
    'Eagle Eye': 'You gain +2 to VIGILANCE when trying to interpret a situation you are not involved in.',
    'Elementary': 'Once per session you can ask the Gamemaster to explain how clues are connected.',
    'Focused': 'Ignore penalties from Conditions when making INVESTIGATION tests.',
    // Servant
    'Loyal': 'Gain +2 on Fear tests in the presence of someone you have sworn to protect.',
    'Robust': 'You may ignore penalties for physical Conditions on one roll per gaming session.',
    'Tough as Nails': 'Gain +2 to FORCE when fighting unarmed.',
    // Vagabond
    'Hobo Tricks': 'Gain +2 to STEALTH when trying to hide yourself or an object from a wealthy human.',
    'Suspicious': 'Ignore mental Conditions when making VIGILANCE tests.',
    'Well-traveled': 'Once per mystery you can make a MANIPULATION test to create an NPC who is situated in the area, and who you have met before.',
    // Writer
    'Automatic Writing': 'Use INSPIRATION to gain clues by channeling spirits through automatic writing.',
    'Journalist': 'You may use INSPIRATION instead of MANIPULATION when charming or deceiving someone to gain information.',
    'Wordsmith': 'Ignore penalties from Conditions when making INSPIRATION tests.',
    // General
    'Battle Experience': 'Gain +2 to MEDICINE when treating a physical critical injury.',
    'Brave': 'Gain +1 to all Fear tests.',
    'Combat-Trained': 'Gain +2 to CLOSE COMBAT and FORCE when parrying.',
    'Contacts': 'Once per session you can decide that you already know a certain NPC, and that your relationship is a positive one.',
    'Coward': 'When wounded in combat, you can make another player character take damage in your stead by passing a STEALTH test.',
    'Deceptive': 'Gain +2 to MANIPULATION when cheating and deceiving.',
    'Dedicated': 'Once per session you can ignore the mental Conditions from a skill test.',
    'Defensive': 'Each turn you get one extra action that may only be used to dodge or parry.',
    'Dual Weapons': 'When using dual weapons in close combat, you can use extra successes to hit an additional enemy in the same zone.',
    'Dynamiter': 'Gain +2 to RANGED COMBAT when using explosives.',
    'Empathetic': 'Ignore penalties from Conditions when making OBSERVATION tests.',
    'Escape Artist': 'Ignore penalties from Conditions when using AGILITY to flee.',
    'Famous': 'Gain +2 to MANIPULATION when trying to influence someone who has heard of you.',
    'Fleet-Footed': 'During combat you may move within your own zone without using actions.',
    'Holy Symbol': 'You have a religious item that allows you to use INSPIRATION to attack vaesen in close combat, dealing 1 damage.',
    'Lightning Reflexes': 'You can draw weapons without using an action.',
    'Nine Lives': 'When rolling for a critical injury, you may decide which of the dice represents the tens and which represents the ones.',
    'Pet': 'You have a pet that you can use once per session to gain +1 to a test of your choice.',
    'Pugilist': 'Deal 1 extra damage when fighting unarmed.',
    'Safety in Numbers': 'Gain +2 to Fear tests when accompanied by at least two other player characters.',
    'Sixth Sense': 'When making INVESTIGATION tests you may spend extra successes to learn if a vaesen has been in the area.',
    'Sprinter': 'Gain +2 to AGILITY when trying to outrun or chase down someone.',
    "The Lord's Shepherd": 'Gain +2 when using INSPIRATION to treat a mental critical injury.',
    'Wealthy': 'Increase Resources by 1 (can be purchased multiple times).'
};

export const PHYSICAL_CRITICAL_INJURIES: DefectInsight[] = [
    { name: 'Limp', description: 'AGILITY -1', type: 'physical' },
    { name: 'Crooked Fingers', description: 'CLOSE COMBAT -1', type: 'physical' },
    { name: 'Reduced Mobility', description: 'AGILITY -1', type: 'physical' },
    { name: 'Skewed Walk', description: 'AGILITY -1', type: 'physical' },
    { name: 'False Joint', description: 'FORCE -1', type: 'physical' },
    { name: 'Ulcer', description: 'INSPIRATION -1', type: 'physical' },
    { name: 'Disfigured', description: 'MANIPULATION -1', type: 'physical' },
    { name: 'Wheezing', description: 'STEALTH -1', type: 'physical' },
    { name: 'Impaired Eyesight', description: 'VIGILANCE -1', type: 'physical' },
    { name: 'Crooked Arm', description: 'RANGED COMBAT -1', type: 'physical' },
    { name: 'Deformed Face', description: 'MANIPULATION -1', type: 'physical' },
    { name: 'Tremor', description: 'RANGED COMBAT -1', type: 'physical' },
    { name: 'Toothless', description: 'INSPIRATION -1', type: 'physical' },
    { name: 'Impaired Balance', description: 'CLOSE COMBAT -1', type: 'physical' },
    { name: 'Drooling', description: 'INSPIRATION -1', type: 'physical' },
    { name: 'Hunchback', description: 'AGILITY -1', type: 'physical' },
    { name: 'Finger Stumps', description: 'RANGED COMBAT -1', type: 'physical' },
    { name: 'Pain', description: 'FORCE -1', type: 'physical' },
    { name: 'Impaired Hearing', description: 'VIGILANCE -1', type: 'physical' },
    { name: 'Stiff Body', description: 'CLOSE COMBAT -1', type: 'physical' },
    { name: 'Sepsis', description: 'FORCE -1', type: 'physical' },
    { name: 'Gangrene', description: 'AGILITY -1', type: 'physical' },
    { name: 'Incontinence', description: 'AGILITY -1', type: 'physical' },
    { name: 'One-Eyed', description: 'VIGILANCE -1', type: 'physical' },
    { name: 'Colostomy Bag', description: 'AGILITY -1', type: 'physical' },
    { name: 'One-Armed', description: 'FORCE -1 (cannot use two-handed weapons)', type: 'physical' },
    { name: 'Phobia of Blood', description: 'Fear -2', type: 'physical' },
    { name: 'Anemia', description: 'FORCE -2', type: 'physical' },
    { name: 'Altered Personality', description: 'OBSERVATION -2', type: 'physical' },
    { name: 'Brain Damage', description: 'LEARNING -2', type: 'physical' },
    { name: 'Prophetic Vision', description: 'INVESTIGATION +3', type: 'physical' },
    { name: 'Living Dead', description: 'STEALTH +3', type: 'physical' },
    { name: 'Supernatural Focus', description: 'RANGED COMBAT +3', type: 'physical' },
    { name: 'Champion', description: 'CLOSE COMBAT +3', type: 'physical' },
    { name: 'Guardian Angel', description: 'AGILITY +4', type: 'physical' },
    { name: 'Supernatural Strength', description: 'FORCE +4', type: 'physical' },
];

export const MENTAL_CRITICAL_INJURIES: DefectInsight[] = [
    { name: 'Dazed', description: 'INVESTIGATION -1', type: 'mental' },
    { name: 'Sensitive to Stress', description: 'STEALTH -1', type: 'mental' },
    { name: 'Fanatic', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Clumsy', description: 'AGILITY -1', type: 'mental' },
    { name: 'Claustrophobic', description: 'STEALTH -1', type: 'mental' },
    { name: 'Skittish', description: 'Fear -1', type: 'mental' },
    { name: 'Compulsive Liar', description: 'INSPIRATION -1', type: 'mental' },
    { name: 'Mask of Terror', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Aged', description: 'OBSERVATION -1', type: 'mental' },
    { name: 'Shattered Confidence', description: 'INSPIRATION -1', type: 'mental' },
    { name: 'Lacks Initiative', description: 'INVESTIGATION -1', type: 'mental' },
    { name: 'Tremor', description: 'RANGED COMBAT -1', type: 'mental' },
    { name: 'Fear of Death', description: 'CLOSE COMBAT -1', type: 'mental' },
    { name: 'Impaired Impulse Control', description: 'STEALTH -1', type: 'mental' },
    { name: 'Hears Voices', description: 'LEARNING -1', type: 'mental' },
    { name: 'Hates Filth', description: 'MEDICINE -1', type: 'mental' },
    { name: 'Sentimental', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Weakened Immune System', description: 'FORCE -1', type: 'mental' },
    { name: 'High-Strung', description: 'AGILITY -1', type: 'mental' },
    { name: 'PTSD', description: 'Fear -1', type: 'mental' },
    { name: 'Capricious', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Lack of Trust', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Paranoid', description: 'VIGILANCE -1', type: 'mental' },
    { name: 'Impaired Empathy', description: 'INSPIRATION -1', type: 'mental' },
    { name: 'Self-Loathing', description: 'MANIPULATION -1', type: 'mental' },
    { name: 'Egocentric', description: 'MEDICINE -1', type: 'mental' },
    { name: 'Dissociating', description: 'RANGED COMBAT -2', type: 'mental' },
    { name: 'Nightmares', description: 'Fear -2', type: 'mental' },
    { name: 'Regressing', description: 'LEARNING -2', type: 'mental' },
    { name: 'Mortified', description: 'MEDICINE -2', type: 'mental' },
    { name: 'Healer', description: 'MEDICINE +3', type: 'mental' },
    { name: 'Haunted', description: 'LEARNING +3', type: 'mental' },
    { name: 'All-Seeing', description: 'INVESTIGATION +3', type: 'mental' },
    { name: 'Divine Messenger', description: 'INSPIRATION +3', type: 'mental' },
    { name: 'Absolute Empathy', description: 'OBSERVATION +4', type: 'mental' },
    { name: 'Enlightened', description: 'LEARNING +4', type: 'mental' },
];